spring:

  application:
    name: front-office

  cloud:
      zookeeper:
        connect-string: zookeeper:2181
        discovery:
          enabled: true

  zipkin:
    baseUrl: http://zipkin:9411/

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

treatment-api:
  ribbon:
    # see com.netflix.client.config.DefaultClientConfigImpl.java for default values
    ServerListRefreshInterval: 5000
    ConnectTimeout: 1000
    ReadTimeout: 2000
    retryableStatusCodes: 503, 504
