spring:

  application:
    name: treatment-api
    base-url: http://localhost

  cloud:
      zookeeper:
        connect-string: zookeeper:2181
        discovery:
          enabled: true

  data:
    mongodb:
      uri: mongodb://asylumdb:27017/test


  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  zipkin:
    baseUrl: http://zipkin:9411/
    # to use service discovery, change value to "http://zipkinserver/"

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
