version: '2'
services:
  nginx:
    image: "nginx:1.13"
    ports:
    - "80:80"
    - "443:443" # ssl handshake
    links:
    - "api:asylumapi"
    volumes:
    #- "/host/path:/docker/path"
    - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
  api:
    build: .
    ports:
    - "8080:8080"
    - "8000:8000" # remote debug
    #volumnes:
    #  .:/code
    links:
    - "db:asylumdb" # db service will be reachable with hosts "db" and "asylumdb"
    environment:
    - "APP_BASE_URL=http://localhost/api" # overload application propertry "app.base-url"
  db:
    image: "mongo:3.0"
    command: --smallfiles
  redis:
    image: "redis:4.0"
    ports:
    - "6379:6379"
  redis-commander:
    image: "rediscommander/redis-commander:latest"
    links:
    - "redis:redis"    
    ports:
    - "8081:8081"
    environment:
    - "REDIS_HOSTS=local:redis:6379"

