version: '2'
services:

  nginx:
    image: "nginx:1.13"
    ports:
    - "80:80"
    - "443:443" # ssl handshake
    links:
    - "treatment-api"
    volumes:
    #- "/host/path:/docker/path"
    - "./ext/nginx/default.conf:/etc/nginx/conf.d/default.conf"

  zookeeper:
    image: "zookeeper:3.4"
    restart: always
    ports:
      - 2181:2181

  front-office:
    build: ./ext/spring-boot
    volumes:
    - "./front-office/build/libs/front-office-0.0.1-SNAPSHOT.jar:/app.jar"
    ports:
    - "8085:8080"
    - "8005:8000" # remote debug
    links:
    - "zookeeper"
    - "treatment-api"

  treatment-api:
    build: ./ext/spring-boot
    volumes:
    - "./treatment/treatment-api/build/libs/treatment-api-0.0.1-SNAPSHOT.jar:/app.jar"
    ports:
    - "8080"
    #- "8000:8000" # remote debug
    links:
    - "zookeeper"
    - "db:asylumdb" # db service will be reachable with hosts "db" and "asylumdb"
    environment:
    - "TREATMENT_API_BASE_URL=http://localhost/api" # overload application propertry "app.base-url"

  #logistic-api:
  #  build: ./etc/spring-boot
  #  ports:
  #  - "8081:8080"
  #  - "8001:8000" # remote debug
  #  links:
  #  - "db:asylumdb" # db service will be reachable with hosts "db" and "asylumdb"
  #  volumes:
  #  - "./logistic/logistic-api/build/libs/logistic-api-0.1.jar:/app.jar"

  db:
    image: "mongo:3.0"
    command: --smallfiles

  redis:
    image: "redis:4.0"
    ports:
    - "6379:6379"
  #redis-commander:
  #  image: "rediscommander/redis-commander:latest"
  #  links:
  #  - "redis:redis"
  #  ports:
  #  - "6380:8081"
  #  environment:
  #  - "REDIS_HOSTS=local:redis:6379"

  #elasticsearch:
  #  image: "elasticsearch:5.6"
  #  ports:
  #  - "9200:9200"
  #  - "9300:9300"
  #kibana:
  #  image: "kibana:5.6"
  #  ports:
  #  - "5601:5601"
  #  links:
  #  - elasticsearch
  #logstash:
  #  image: "logstash:5.6"
  #  ports:
  #  - "5000:5000"
  #  links:
  #  - elasticsearch
  #  volumes:
  #  - ./ext/logstash:/etc/logstash/conf.d
  #  command: logstash -f /etc/logstash/conf.d/logstash.conf
  zipkin:
    image: openzipkin/zipkin
    ports:
    - "9411:9411"


  #zookeeper-web:
  #  image: elkozmon/zoonavigator-web:latest
  #  ports:
  #   - "9000:8000"
  #  environment:
  #    API_HOST: "zookeeper-api"
  #    API_PORT: 9000
  #  links:
  #   - zookeeper-api
  #  restart: always
  #zookeeper-api:
  #  image: elkozmon/zoonavigator-api:latest
  #  environment:
  #    SERVER_HTTP_PORT: 9000
  #  restart: always
