version: '2'
services:
  nginx:
    image: "nginx:1.13"
    ports:
    - "80:80"
    - "443:443" # ssl handshake
    links:
    - "api:asylumapi"
    volumes:
    #- "/host/path:/docker/path"
    - "./ext/nginx/default.conf:/etc/nginx/conf.d/default.conf"
  api:
    build: ./ext/spring-boot
    volumes:
    - "./treatment/treatment-api/build/libs/treatment-api-0.0.1-SNAPSHOT.jar:/app.jar"
    ports:
    - "8080:8080"
    - "8000:8000" # remote debug
    links:
    - "db:asylumdb" # db service will be reachable with hosts "db" and "asylumdb"
    environment:
    - "APP_BASE_URL=http://localhost/api" # overload application propertry "app.base-url"
  #logistic-api:
  #  build: ./etc/spring-boot
  #  ports:
  #  - "8081:8080"
  #  - "8001:8000" # remote debug
  #  links:
  #  - "db:asylumdb" # db service will be reachable with hosts "db" and "asylumdb"
  #  volumes:
  #  - "./logistic/logistic-api/build/libs/logistic-api-0.1.jar:/app.jar"
  db:
    image: "mongo:3.0"
    command: --smallfiles
  redis:
    image: "redis:4.0"
    ports:
    - "6379:6379"
  redis-commander:
    image: "rediscommander/redis-commander:latest"
    links:
    - "redis:redis"    
    ports:
    - "8081:8081"
    environment:
    - "REDIS_HOSTS=local:redis:6379"

