package poc.arkham.common.web.util;

import org.springframework.http.converter.HttpMessageNotReadableException;
import org.springframework.util.StringUtils;

/**
 * <p>Utilities used to validate the user's request.</p>
 * <p>It should not be used to check the consistency of business entities, but rather to indicate that the api is not used as intended.
 * </p>
 * <p>e.g. A user post a new record with an id, though the id should be generated by the system.</p>
 */
public class RestPreconditions {

    public static void validateNotNull(String value, String field) {
        if (value == null) {
            throw new HttpMessageNotReadableException(field + " must not be null");
        }
    }

    public static void validateNull(String value, String field) {
        if (value != null) {
            throw new HttpMessageNotReadableException(field + " must be null");
        }
    }

    public static void validateNotEmpty(String value, String field) {
        if (StringUtils.isEmpty(value)) {
            throw new HttpMessageNotReadableException(field + " must not be null or empty");
        }
    }

    public static void validate(boolean test, String errorMessage) {
        if (!test) {
            throw new HttpMessageNotReadableException(errorMessage);
        }
    }

}
